--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/12/2017 14:36:36
-- Server version: 5.5.5-10.1.21-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE mvc;

--
-- Definition for table entradas
--
DROP TABLE IF EXISTS entradas;
CREATE TABLE entradas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) DEFAULT NULL,
  texto VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

--
-- Definition for table noticias
--
DROP TABLE IF EXISTS noticias;
CREATE TABLE noticias (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Titulo VARCHAR(255) DEFAULT NULL,
  TextoCorto VARCHAR(255) DEFAULT NULL,
  TextoLargo VARCHAR(255) DEFAULT NULL,
  Fecha DATE DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

-- 
-- Dumping data for table entradas
--
INSERT INTO entradas VALUES
(1, 'Entrada 1', 'Esta es la primera entrada'),
(2, 'Entrada 2', 'Segunda entrada');

-- 
-- Dumping data for table noticias
--
INSERT INTO noticias VALUES
(1, 'Noticia 1', NULL, 'Esta es la noticia que comienza la lista', '2017-12-13'),
(2, 'Noticia 2', NULL, 'Esta es la noticia segunda. No tiene mas que lo que ves', '2017-12-05'),
(3, 'titulo', '...', 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', '0000-00-00');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;