-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/12/2017 16:12:18
-- Server version: 5.5.5-10.1.16-MariaDB
-- Client version: 4.1

--
-- Definition for database mvc3
--
DROP DATABASE IF EXISTS mvc4;
CREATE DATABASE IF NOT EXISTS mvc4
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE mvc4;

--
-- Definition for table entradas
--
CREATE TABLE IF NOT EXISTS entradas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Titulo VARCHAR(255) DEFAULT NULL,
  Texto VARCHAR(255) DEFAULT NULL,
  Foto VARCHAR(255) DEFAULT NULL,
  portada BIT(1) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table noticias
--
CREATE TABLE IF NOT EXISTS noticias (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Titulo VARCHAR(255) DEFAULT NULL,
  Texto VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table usuarios
--
CREATE TABLE IF NOT EXISTS usuarios (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(255) DEFAULT NULL,
  Login VARCHAR(255) DEFAULT NULL,
  Password VARCHAR(255) DEFAULT NULL,
  direccion VARCHAR(255) DEFAULT NULL,
  foto VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table entradas
--
INSERT INTO entradas VALUES
(1, 'Estamos abiertos', 'Ya hemos comenzado a preparar ', 'entrada1.jpg', True);

-- 
-- Dumping data for table noticias
--
INSERT INTO noticias VALUES
(1, 'Noticia 1', 'Esta es la noticia 1'),
(2, NULL, NULL);

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'Ramon', 'RamonAbramo', 'facil', 'Ruiz de Alda', 'usuario1.jpg');

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;